CREATE TABLE `Submissions` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`FIRST_NAME`	TEXT NOT NULL,
	`LAST_NAME`	TEXT NOT NULL,
	`POSTCODE`	VARCHAR(10) NOT NULL,
	`AMOUNT`	FLOAT NOT NULL,
	`REASON`	TEXT NOT NULL
);